name: FTP Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Build static assets
        run: pnpm build
        env:
          MAPBOX_API_TOKEN: ${{ secrets.MAPBOX_API_TOKEN }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ftp.imh.co.uk
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
